steps:
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', 'fir-oss/static-renderer', '.' ]
- name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args: ['-c', 'docker run -e fir-oss/static-renderer']
  secretEnv:
    - TOKEN
