timeout: 1800s
steps:
- name: 'node:12'
  entrypoint: 'npm'
  args: ['install']
- name: 'node:12'
  entrypoint: 'npm'
  args: ['--prefix=frontend', 'install']
- name: 'node:12'
  entrypoint: 'npm'
  args: ['--prefix=frontend', 'run', 'build']
- name: 'node:12'
  entrypoint: 'npm'
  args: ['--prefix=frontend', 'run', 'deploy:hosting']
